// @generated by schema-rust-next

#[rustfmt::skip]
pub type String = std::string::String;
#[rustfmt::skip]
pub type Integer = u64;
#[rustfmt::skip]
pub type Boolean = bool;
#[rustfmt::skip]
pub type Path = std::string::String;

#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentName as ComponentName;
#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentKind as ComponentKind;
#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentHealth as ComponentHealth;
#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentDesiredState as ComponentDesiredState;
#[rustfmt::skip]
pub use signal_persona::schema::lib::ComponentStatus as LifecycleComponentStatus;
#[rustfmt::skip]
pub use signal_persona::schema::lib::EngineIdentifier as EngineIdentifier;

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
pub use nota::{NotaDecodeError, NotaEncode, NotaSource};

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Launch(EngineLaunch);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Query(MetaQuery);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retire(EngineIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Start(ComponentStartup);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Stop(ComponentShutdown);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Launched(LaunchAcceptance);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaunchRejected(LaunchRejection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Catalog(EngineCatalog);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineStatus(EngineStatusReport);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentStatus(LifecycleComponentStatus);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentMissing(ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct Retired(EngineIdentifier);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetireRejected(RetirementRejection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActionAccepted(ActionAcceptance);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActionRejected(ActionRejection);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineGeneration(u64);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EnginePhase {
    Starting,
    Running,
    Degraded,
    Draining,
    Stopped,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineStatusReport {
    pub generation: EngineGeneration,
    pub phase: EnginePhase,
    pub components: Vec<LifecycleComponentStatus>,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EngineStatusScope {
    WholeEngine,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum EngineCatalogScope {
    AllEngines,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineLabel(String);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineLaunch(EngineLabel);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum MetaQuery {
    Catalog(EngineCatalogScope),
    EngineStatus(EngineStatusScope),
    ComponentStatus(ComponentName),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum LaunchRejectionReason {
    EngineLabelAlreadyExists,
    EngineLimitReached,
    LaunchPlanRejected,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaunchAcceptance {
    pub engine: EngineIdentifier,
    pub label: EngineLabel,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct LaunchRejection {
    pub label: EngineLabel,
    pub reason: LaunchRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum RetirementRejectionReason {
    EngineNotFound,
    EngineStillRunning,
    EngineHasLiveRoutes,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct RetirementRejection {
    pub engine: EngineIdentifier,
    pub reason: RetirementRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineCatalogEntry {
    pub engine: EngineIdentifier,
    pub label: EngineLabel,
    pub phase: EnginePhase,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct EngineCatalog(Vec<EngineCatalogEntry>);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentStartup(ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ComponentShutdown(ComponentName);

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActionAcceptance {
    pub component: ComponentName,
    pub desired_state: ComponentDesiredState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum ActionRejectionReason {
    ComponentNotManaged,
    ComponentAlreadyInDesiredState,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub struct ActionRejection {
    pub component: ComponentName,
    pub reason: ActionRejectionReason,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Input {
    Launch(Launch),
    Query(Query),
    Retire(Retire),
    Start(Start),
    Stop(Stop),
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize, Clone, Debug, PartialEq, Eq)]
pub enum Output {
    Launched(Launched),
    LaunchRejected(LaunchRejected),
    Catalog(Catalog),
    EngineStatus(EngineStatus),
    ComponentStatus(ComponentStatus),
    ComponentMissing(ComponentMissing),
    Retired(Retired),
    RetireRejected(RetireRejected),
    ActionAccepted(ActionAccepted),
    ActionRejected(ActionRejected),
}

#[rustfmt::skip]
impl Launch {
    pub fn new(payload: EngineLaunch) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineLaunch {
        &self.0
    }
    pub fn into_payload(self) -> EngineLaunch {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineLaunch> for Launch {
    fn from(payload: EngineLaunch) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Query {
    pub fn new(payload: MetaQuery) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &MetaQuery {
        &self.0
    }
    pub fn into_payload(self) -> MetaQuery {
        self.0
    }
}
#[rustfmt::skip]
impl From<MetaQuery> for Query {
    fn from(payload: MetaQuery) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retire {
    pub fn new(payload: EngineIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> EngineIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineIdentifier> for Retire {
    fn from(payload: EngineIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Start {
    pub fn new(payload: ComponentStartup) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentStartup {
        &self.0
    }
    pub fn into_payload(self) -> ComponentStartup {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentStartup> for Start {
    fn from(payload: ComponentStartup) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Stop {
    pub fn new(payload: ComponentShutdown) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentShutdown {
        &self.0
    }
    pub fn into_payload(self) -> ComponentShutdown {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentShutdown> for Stop {
    fn from(payload: ComponentShutdown) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Launched {
    pub fn new(payload: LaunchAcceptance) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaunchAcceptance {
        &self.0
    }
    pub fn into_payload(self) -> LaunchAcceptance {
        self.0
    }
}
#[rustfmt::skip]
impl From<LaunchAcceptance> for Launched {
    fn from(payload: LaunchAcceptance) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl LaunchRejected {
    pub fn new(payload: LaunchRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LaunchRejection {
        &self.0
    }
    pub fn into_payload(self) -> LaunchRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<LaunchRejection> for LaunchRejected {
    fn from(payload: LaunchRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Catalog {
    pub fn new(payload: EngineCatalog) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineCatalog {
        &self.0
    }
    pub fn into_payload(self) -> EngineCatalog {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineCatalog> for Catalog {
    fn from(payload: EngineCatalog) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineStatus {
    pub fn new(payload: EngineStatusReport) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineStatusReport {
        &self.0
    }
    pub fn into_payload(self) -> EngineStatusReport {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineStatusReport> for EngineStatus {
    fn from(payload: EngineStatusReport) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentStatus {
    pub fn new(payload: LifecycleComponentStatus) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &LifecycleComponentStatus {
        &self.0
    }
    pub fn into_payload(self) -> LifecycleComponentStatus {
        self.0
    }
}
#[rustfmt::skip]
impl From<LifecycleComponentStatus> for ComponentStatus {
    fn from(payload: LifecycleComponentStatus) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentMissing {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for ComponentMissing {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl Retired {
    pub fn new(payload: EngineIdentifier) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineIdentifier {
        &self.0
    }
    pub fn into_payload(self) -> EngineIdentifier {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineIdentifier> for Retired {
    fn from(payload: EngineIdentifier) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl RetireRejected {
    pub fn new(payload: RetirementRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &RetirementRejection {
        &self.0
    }
    pub fn into_payload(self) -> RetirementRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<RetirementRejection> for RetireRejected {
    fn from(payload: RetirementRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActionAccepted {
    pub fn new(payload: ActionAcceptance) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ActionAcceptance {
        &self.0
    }
    pub fn into_payload(self) -> ActionAcceptance {
        self.0
    }
}
#[rustfmt::skip]
impl From<ActionAcceptance> for ActionAccepted {
    fn from(payload: ActionAcceptance) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ActionRejected {
    pub fn new(payload: ActionRejection) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ActionRejection {
        &self.0
    }
    pub fn into_payload(self) -> ActionRejection {
        self.0
    }
}
#[rustfmt::skip]
impl From<ActionRejection> for ActionRejected {
    fn from(payload: ActionRejection) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineGeneration {
    pub fn new(payload: u64) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &u64 {
        &self.0
    }
    pub fn into_payload(self) -> u64 {
        self.0
    }
}
#[rustfmt::skip]
impl From<u64> for EngineGeneration {
    fn from(payload: u64) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineLabel {
    pub fn new(payload: impl Into<String>) -> Self {
        Self(payload.into())
    }
    pub fn payload(&self) -> &String {
        &self.0
    }
    pub fn into_payload(self) -> String {
        self.0
    }
}
#[rustfmt::skip]
impl From<String> for EngineLabel {
    fn from(payload: String) -> Self {
        Self::new(payload)
    }
}
#[rustfmt::skip]
impl std::fmt::Display for EngineLabel {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.payload().fmt(formatter)
    }
}
#[rustfmt::skip]
impl AsRef<str> for EngineLabel {
    fn as_ref(&self) -> &str {
        self.payload().as_str()
    }
}
#[rustfmt::skip]
impl PartialEq<&str> for EngineLabel {
    fn eq(&self, other: &&str) -> bool {
        self.payload() == other
    }
}

#[rustfmt::skip]
impl EngineLaunch {
    pub fn new(payload: EngineLabel) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &EngineLabel {
        &self.0
    }
    pub fn into_payload(self) -> EngineLabel {
        self.0
    }
}
#[rustfmt::skip]
impl From<EngineLabel> for EngineLaunch {
    fn from(payload: EngineLabel) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl EngineCatalog {
    pub fn new(payload: Vec<EngineCatalogEntry>) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &Vec<EngineCatalogEntry> {
        &self.0
    }
    pub fn into_payload(self) -> Vec<EngineCatalogEntry> {
        self.0
    }
}
#[rustfmt::skip]
impl From<Vec<EngineCatalogEntry>> for EngineCatalog {
    fn from(payload: Vec<EngineCatalogEntry>) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentStartup {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for ComponentStartup {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl ComponentShutdown {
    pub fn new(payload: ComponentName) -> Self {
        Self(payload)
    }
    pub fn payload(&self) -> &ComponentName {
        &self.0
    }
    pub fn into_payload(self) -> ComponentName {
        self.0
    }
}
#[rustfmt::skip]
impl From<ComponentName> for ComponentShutdown {
    fn from(payload: ComponentName) -> Self {
        Self::new(payload)
    }
}

#[rustfmt::skip]
impl MetaQuery {
    pub fn catalog(payload: EngineCatalogScope) -> Self {
        Self::Catalog(payload)
    }
    pub fn engine_status(payload: EngineStatusScope) -> Self {
        Self::EngineStatus(payload)
    }
    pub fn component_status(payload: ComponentName) -> Self {
        Self::ComponentStatus(payload)
    }
}

#[rustfmt::skip]
impl Input {
    pub fn launch(payload: EngineLaunch) -> Self {
        Self::Launch(Launch::new(payload))
    }
    pub fn query(payload: MetaQuery) -> Self {
        Self::Query(Query::new(payload))
    }
    pub fn retire(payload: EngineIdentifier) -> Self {
        Self::Retire(Retire::new(payload))
    }
    pub fn start(payload: ComponentStartup) -> Self {
        Self::Start(Start::new(payload))
    }
    pub fn stop(payload: ComponentShutdown) -> Self {
        Self::Stop(Stop::new(payload))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn launched(payload: LaunchAcceptance) -> Self {
        Self::Launched(Launched::new(payload))
    }
    pub fn launch_rejected(payload: LaunchRejection) -> Self {
        Self::LaunchRejected(LaunchRejected::new(payload))
    }
    pub fn catalog(payload: EngineCatalog) -> Self {
        Self::Catalog(Catalog::new(payload))
    }
    pub fn engine_status(payload: EngineStatusReport) -> Self {
        Self::EngineStatus(EngineStatus::new(payload))
    }
    pub fn component_status(payload: LifecycleComponentStatus) -> Self {
        Self::ComponentStatus(ComponentStatus::new(payload))
    }
    pub fn component_missing(payload: ComponentName) -> Self {
        Self::ComponentMissing(ComponentMissing::new(payload))
    }
    pub fn retired(payload: EngineIdentifier) -> Self {
        Self::Retired(Retired::new(payload))
    }
    pub fn retire_rejected(payload: RetirementRejection) -> Self {
        Self::RetireRejected(RetireRejected::new(payload))
    }
    pub fn action_accepted(payload: ActionAcceptance) -> Self {
        Self::ActionAccepted(ActionAccepted::new(payload))
    }
    pub fn action_rejected(payload: ActionRejection) -> Self {
        Self::ActionRejected(ActionRejected::new(payload))
    }
}

#[rustfmt::skip]
impl From<EngineCatalogScope> for MetaQuery {
    fn from(payload: EngineCatalogScope) -> Self {
        Self::Catalog(payload)
    }
}

#[rustfmt::skip]
impl From<EngineStatusScope> for MetaQuery {
    fn from(payload: EngineStatusScope) -> Self {
        Self::EngineStatus(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentName> for MetaQuery {
    fn from(payload: ComponentName) -> Self {
        Self::ComponentStatus(payload)
    }
}

#[rustfmt::skip]
impl From<Launch> for Input {
    fn from(payload: Launch) -> Self {
        Self::Launch(payload)
    }
}

#[rustfmt::skip]
impl From<Query> for Input {
    fn from(payload: Query) -> Self {
        Self::Query(payload)
    }
}

#[rustfmt::skip]
impl From<Retire> for Input {
    fn from(payload: Retire) -> Self {
        Self::Retire(payload)
    }
}

#[rustfmt::skip]
impl From<Start> for Input {
    fn from(payload: Start) -> Self {
        Self::Start(payload)
    }
}

#[rustfmt::skip]
impl From<Stop> for Input {
    fn from(payload: Stop) -> Self {
        Self::Stop(payload)
    }
}

#[rustfmt::skip]
impl From<Launched> for Output {
    fn from(payload: Launched) -> Self {
        Self::Launched(payload)
    }
}

#[rustfmt::skip]
impl From<LaunchRejected> for Output {
    fn from(payload: LaunchRejected) -> Self {
        Self::LaunchRejected(payload)
    }
}

#[rustfmt::skip]
impl From<Catalog> for Output {
    fn from(payload: Catalog) -> Self {
        Self::Catalog(payload)
    }
}

#[rustfmt::skip]
impl From<EngineStatus> for Output {
    fn from(payload: EngineStatus) -> Self {
        Self::EngineStatus(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentStatus> for Output {
    fn from(payload: ComponentStatus) -> Self {
        Self::ComponentStatus(payload)
    }
}

#[rustfmt::skip]
impl From<ComponentMissing> for Output {
    fn from(payload: ComponentMissing) -> Self {
        Self::ComponentMissing(payload)
    }
}

#[rustfmt::skip]
impl From<Retired> for Output {
    fn from(payload: Retired) -> Self {
        Self::Retired(payload)
    }
}

#[rustfmt::skip]
impl From<RetireRejected> for Output {
    fn from(payload: RetireRejected) -> Self {
        Self::RetireRejected(payload)
    }
}

#[rustfmt::skip]
impl From<ActionAccepted> for Output {
    fn from(payload: ActionAccepted) -> Self {
        Self::ActionAccepted(payload)
    }
}

#[rustfmt::skip]
impl From<ActionRejected> for Output {
    fn from(payload: ActionRejected) -> Self {
        Self::ActionRejected(payload)
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Input {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Input {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::str::FromStr for Output {
    type Err = NotaDecodeError;
    fn from_str(source: &str) -> Result<Self, Self::Err> {
        NotaSource::new(source).parse::<Self>()
    }
}
#[rustfmt::skip]
#[cfg(feature = "nota-text")]
impl std::fmt::Display for Output {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(&<Self as NotaEncode>::to_nota(self))
    }
}

#[rustfmt::skip]
pub mod short_header {
    pub const INPUT_LAUNCH: u64 = 0x0000000000000000;
    pub const INPUT_QUERY: u64 = 0x0001000000000000;
    pub const INPUT_RETIRE: u64 = 0x0002000000000000;
    pub const INPUT_START: u64 = 0x0003000000000000;
    pub const INPUT_STOP: u64 = 0x0004000000000000;
    pub const OUTPUT_LAUNCHED: u64 = 0x0100000000000000;
    pub const OUTPUT_LAUNCH_REJECTED: u64 = 0x0101000000000000;
    pub const OUTPUT_CATALOG: u64 = 0x0102000000000000;
    pub const OUTPUT_ENGINE_STATUS: u64 = 0x0103000000000000;
    pub const OUTPUT_COMPONENT_STATUS: u64 = 0x0104000000000000;
    pub const OUTPUT_COMPONENT_MISSING: u64 = 0x0105000000000000;
    pub const OUTPUT_RETIRED: u64 = 0x0106000000000000;
    pub const OUTPUT_RETIRE_REJECTED: u64 = 0x0107000000000000;
    pub const OUTPUT_ACTION_ACCEPTED: u64 = 0x0108000000000000;
    pub const OUTPUT_ACTION_REJECTED: u64 = 0x0109000000000000;
}

#[rustfmt::skip]
const SIGNAL_SHORT_HEADER_BYTE_COUNT: usize = 8;
#[rustfmt::skip]
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum SignalFrameError {
    ArchiveEncode,
    ArchiveDecode,
    FrameTooShort { found: usize },
    UnknownHeader { root_enum: &'static str, header: u64 },
    HeaderMismatch { expected: u64, found: u64 },
}
#[rustfmt::skip]
impl std::fmt::Display for SignalFrameError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::ArchiveEncode => formatter.write_str("failed to encode rkyv archive"),
            Self::ArchiveDecode => formatter.write_str("failed to decode rkyv archive"),
            Self::FrameTooShort { found } => {
                write!(formatter, "signal frame too short: {found} bytes")
            }
            Self::UnknownHeader { root_enum, header } => {
                write!(formatter, "unknown {root_enum} short header 0x{header:016X}")
            }
            Self::HeaderMismatch { expected, found } => {
                write!(
                    formatter,
                    "decoded payload header mismatch: expected 0x{expected:016X}, found 0x{found:016X}"
                )
            }
        }
    }
}
#[rustfmt::skip]
impl std::error::Error for SignalFrameError {}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum InputRoute {
    Launch,
    Query,
    Retire,
    Start,
    Stop,
}

#[rustfmt::skip]
#[cfg_attr(feature = "nota-text", derive(nota::NotaDecode, nota::NotaEncode))]
#[derive(
    rkyv::Archive,
    rkyv::Serialize,
    rkyv::Deserialize,
    Clone,
    Copy,
    Debug,
    PartialEq,
    Eq,
)]
pub enum OutputRoute {
    Launched,
    LaunchRejected,
    Catalog,
    EngineStatus,
    ComponentStatus,
    ComponentMissing,
    Retired,
    RetireRejected,
    ActionAccepted,
    ActionRejected,
}

#[rustfmt::skip]
impl Input {
    pub fn route(&self) -> InputRoute {
        match self {
            Self::Launch(_) => InputRoute::Launch,
            Self::Query(_) => InputRoute::Query,
            Self::Retire(_) => InputRoute::Retire,
            Self::Start(_) => InputRoute::Start,
            Self::Stop(_) => InputRoute::Stop,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Launch(_) => short_header::INPUT_LAUNCH,
            Self::Query(_) => short_header::INPUT_QUERY,
            Self::Retire(_) => short_header::INPUT_RETIRE,
            Self::Start(_) => short_header::INPUT_START,
            Self::Stop(_) => short_header::INPUT_STOP,
        }
    }
    pub fn route_from_short_header(header: u64) -> Result<InputRoute, SignalFrameError> {
        match header {
            short_header::INPUT_LAUNCH => Ok(InputRoute::Launch),
            short_header::INPUT_QUERY => Ok(InputRoute::Query),
            short_header::INPUT_RETIRE => Ok(InputRoute::Retire),
            short_header::INPUT_START => Ok(InputRoute::Start),
            short_header::INPUT_STOP => Ok(InputRoute::Stop),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Input",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(InputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl Output {
    pub fn route(&self) -> OutputRoute {
        match self {
            Self::Launched(_) => OutputRoute::Launched,
            Self::LaunchRejected(_) => OutputRoute::LaunchRejected,
            Self::Catalog(_) => OutputRoute::Catalog,
            Self::EngineStatus(_) => OutputRoute::EngineStatus,
            Self::ComponentStatus(_) => OutputRoute::ComponentStatus,
            Self::ComponentMissing(_) => OutputRoute::ComponentMissing,
            Self::Retired(_) => OutputRoute::Retired,
            Self::RetireRejected(_) => OutputRoute::RetireRejected,
            Self::ActionAccepted(_) => OutputRoute::ActionAccepted,
            Self::ActionRejected(_) => OutputRoute::ActionRejected,
        }
    }
    pub fn short_header(&self) -> u64 {
        match self {
            Self::Launched(_) => short_header::OUTPUT_LAUNCHED,
            Self::LaunchRejected(_) => short_header::OUTPUT_LAUNCH_REJECTED,
            Self::Catalog(_) => short_header::OUTPUT_CATALOG,
            Self::EngineStatus(_) => short_header::OUTPUT_ENGINE_STATUS,
            Self::ComponentStatus(_) => short_header::OUTPUT_COMPONENT_STATUS,
            Self::ComponentMissing(_) => short_header::OUTPUT_COMPONENT_MISSING,
            Self::Retired(_) => short_header::OUTPUT_RETIRED,
            Self::RetireRejected(_) => short_header::OUTPUT_RETIRE_REJECTED,
            Self::ActionAccepted(_) => short_header::OUTPUT_ACTION_ACCEPTED,
            Self::ActionRejected(_) => short_header::OUTPUT_ACTION_REJECTED,
        }
    }
    pub fn route_from_short_header(
        header: u64,
    ) -> Result<OutputRoute, SignalFrameError> {
        match header {
            short_header::OUTPUT_LAUNCHED => Ok(OutputRoute::Launched),
            short_header::OUTPUT_LAUNCH_REJECTED => Ok(OutputRoute::LaunchRejected),
            short_header::OUTPUT_CATALOG => Ok(OutputRoute::Catalog),
            short_header::OUTPUT_ENGINE_STATUS => Ok(OutputRoute::EngineStatus),
            short_header::OUTPUT_COMPONENT_STATUS => Ok(OutputRoute::ComponentStatus),
            short_header::OUTPUT_COMPONENT_MISSING => Ok(OutputRoute::ComponentMissing),
            short_header::OUTPUT_RETIRED => Ok(OutputRoute::Retired),
            short_header::OUTPUT_RETIRE_REJECTED => Ok(OutputRoute::RetireRejected),
            short_header::OUTPUT_ACTION_ACCEPTED => Ok(OutputRoute::ActionAccepted),
            short_header::OUTPUT_ACTION_REJECTED => Ok(OutputRoute::ActionRejected),
            _ => {
                Err(SignalFrameError::UnknownHeader {
                    root_enum: "Output",
                    header,
                })
            }
        }
    }
    pub fn encode_signal_frame(&self) -> Result<Vec<u8>, SignalFrameError> {
        let archive = rkyv::to_bytes::<rkyv::rancor::Error>(self)
            .map_err(|_| SignalFrameError::ArchiveEncode)?;
        let mut frame = Vec::with_capacity(
            SIGNAL_SHORT_HEADER_BYTE_COUNT + archive.len(),
        );
        frame.extend_from_slice(&self.short_header().to_le_bytes());
        frame.extend_from_slice(&archive);
        Ok(frame)
    }
    pub fn decode_signal_frame(
        frame: &[u8],
    ) -> Result<(OutputRoute, Self), SignalFrameError> {
        if frame.len() < SIGNAL_SHORT_HEADER_BYTE_COUNT {
            return Err(SignalFrameError::FrameTooShort {
                found: frame.len(),
            });
        }
        let mut header_bytes = [0_u8; SIGNAL_SHORT_HEADER_BYTE_COUNT];
        header_bytes.copy_from_slice(&frame[..SIGNAL_SHORT_HEADER_BYTE_COUNT]);
        let header = u64::from_le_bytes(header_bytes);
        let route = Self::route_from_short_header(header)?;
        let value = rkyv::from_bytes::<
            Self,
            rkyv::rancor::Error,
        >(&frame[SIGNAL_SHORT_HEADER_BYTE_COUNT..])
            .map_err(|_| SignalFrameError::ArchiveDecode)?;
        let expected = value.short_header();
        if expected != header {
            return Err(SignalFrameError::HeaderMismatch {
                expected,
                found: header,
            });
        }
        Ok((route, value))
    }
}

#[rustfmt::skip]
impl signal_frame::RequestPayload for Input {}
#[rustfmt::skip]
impl signal_frame::SignalOperationHeads for Input {
    const HEADS: &'static [&'static str] = &[
        "Launch",
        "Query",
        "Retire",
        "Start",
        "Stop",
    ];
}
#[rustfmt::skip]
impl signal_frame::LogVariant for Input {
    fn log_variant(&self) -> u64 {
        self.short_header()
    }
}
#[rustfmt::skip]
pub type Frame = signal_frame::ExchangeFrame<Input, Output>;
#[rustfmt::skip]
pub type FrameBody = signal_frame::ExchangeFrameBody<Input, Output>;
#[rustfmt::skip]
pub type Request = signal_frame::Request<Input>;
#[rustfmt::skip]
pub type ReplyEnvelope = signal_frame::Reply<Output>;
#[rustfmt::skip]
pub type RequestBuilder = signal_frame::RequestBuilder<Input>;
#[rustfmt::skip]
impl Input {
    pub fn into_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let request = signal_frame::Request::from_payload(self);
        Frame::with_short_header(
            short_header,
            FrameBody::Request {
                exchange,
                request,
            },
        )
    }
}
#[rustfmt::skip]
impl Output {
    pub fn into_reply_frame(self, exchange: signal_frame::ExchangeIdentifier) -> Frame {
        let short_header = signal_frame::ShortHeader::new(self.short_header());
        let reply = signal_frame::Reply::committed(
            signal_frame::NonEmpty::single(signal_frame::SubReply::Ok(self)),
        );
        Frame::with_short_header(
            short_header,
            FrameBody::Reply {
                exchange,
                reply,
            },
        )
    }
}
